
name: Speculum Release

on:
  push:
    tags:
      - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Set env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - uses: actions/checkout@v3
    ##########################################
    - name: Install dependencies
      run: lein deps
    - name: Build Release JAR
      run: lein uberjar
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to Github Packages
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GHCR_PAT }}
    - name: Build image and push to GitHub Container Registry
      uses: docker/build-push-action@v2
      with:
        context: .
        tags: |
          ghcr.io/iomonad/speculum:latest
          ghcr.io/iomonad/speculum:${{ github.sha }}
          ghcr.io/iomonad/speculum:${{ env.RELEASE_VERSION }}
        push: true
    - uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GHCR_PAT }}
